### ISSUE TITLE
Loading JustGage in SystemJS

### ISSUE THREAD

**Issue by jaime-marcondes** [emn178/angular2-justgage#2]
Dear Author,

First of all, great work at your library.
We are trying use Justgage in Angular2 with SystemJS module.

_SystemJS.config.js:_
    ...
    map: {
      app: 'app',
      // angular bundles
      '@angular/animations': 'npm:@angular/animations/bundles/animations.umd.js',
      '@angular/animations/browser': 'npm:@angular/animations/bundles/animations-browser.umd.js',
    ...
    ...
      'angular2-justgage':'npm:angular2-justgage',
      'justgage':'npm:justgage',
      'raphael':'npm:raphael'
   }

Shows this error on Console:
_Error: (SystemJS) Unexpected token <
	SyntaxError: Unexpected token <
	    at eval (<anonymous>)
	    at Object.eval (http://127.0.0.1:12345/app/app.module.js:17:27)
	    at eval (http://127.0.0.1:12345/app/app.module.js:49:4)
	    at eval (http://127.0.0.1:12345/app/app.module.js:50:3)
	    at eval (<anonymous>)
	Evaluating http://127.0.0.1:12345/node_modules/angular2-justgage_

Does JustGage works on SystemJS ? 
If you can provide an Snippet, we appreciate...

Thanks for your help.

Jaime

**Comment by emn178** [comment]
try this?
```
{
  map: {
    'angular2-justgage': 'npm:angular2-justgage'
  },
  packages: {
    'angular2-justgage': {
      main: './dist/index.js',
      defaultExtension: 'js'
    }
  }
}
```

**Comment by jaime-marcondes** [comment]
We tried, no success.
The error now shows:

(index):23 Error: (SystemJS) Unexpected token <
	SyntaxError: Unexpected token <
	    at eval (<anonymous>)
	    at Object.eval (http://127.0.0.1:12345/node_modules/angular2-justgage/dist/justgage.module.js:2:21)
	    at eval (http://127.0.0.1:12345/node_modules/angular2-justgage/dist/justgage.module.js:30:4)
	    at eval (http://127.0.0.1:12345/node_modules/angular2-justgage/dist/justgage.module.js:31:3)
	    at eval (<anonymous>)
	Evaluating http://127.0.0.1:12345/node_modules/raphael
	Evaluating http://127.0.0.1:12345/node_modules/angular2-justgage/dist/justgage.module.js

SystemJS.config.js:

  _map: {
      // our app is within the app folder
      app: 'app',
...
      'angular2-justgage': 'npm:angular2-justgage',
      'justgage': 'npm:justgage',
      'raphael': 'npm:raphael'
    },

    // packages tells the System loader how to load when no filename and/or no extension
    packages: {
      app: {
        main: './main.js',
        defaultExtension: 'js'
      },
      rxjs: {
        defaultExtension: 'js'
      },
      'angular2-justgage': {
        main: './dist/index.js',
        defaultExtension: 'js'
      }_


If we solve this, i return more info.
Thanks again!
