### ISSUE TITLE
change max value dynamic problems when max = 0

### ISSUE THREAD

**Issue by MechaAdmin** [emn178/angular2-justgage#4]
Hello,

I'm using justgage on my angular 2 application.
I need to change the max value during the application execution.
Everything works great except when i try to set max = 0, gage dosen't change and it max displayed remains at the last value.
Here my (simple) code: 

```
<justgage [options]="options" [max]="max" [value]="value"></justgage>
<div (click)="remove()">remove</div>
```

```
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'app works!';
	options = {
	  title: 'Visitors'
	};
	max = 5;
	value = 5;
	remove(){
		this.max--;
	}
}

```

**Comment by emn178** [comment]
max should not be 0. justgage will not update max if it is 0.

**Comment by MechaAdmin** [comment]
thanks for the answer, however if i set at the beginning 0 it display correctly, no way to display 0 at run time?

**Comment by emn178** [comment]
I think you can re-create element with max 0.

**Comment by MechaAdmin** [comment]
sorry but how can i re-create element?

**Comment by emn178** [comment]
update options to a new instance. this will re-create justgage element.

**Comment by MechaAdmin** [comment]
yes it works great, thank you so much!
