### ISSUE TITLE
angular2-justgage won't compile AOT in Angular 5

### ISSUE THREAD

**Issue by hhmultimediallc** [emn178/angular2-justgage#5]
Hello.

This is a wonderful tool and we really love it.  But now we have a problem when we upgraded to Angular 5 in that it will not compile --aot.  Uninstalling `angular2-justgage`, removing code and tag references, my app compiles aot perfectly.

One other interesting note:  When `angular2-justgage` is installed, it takes the compiler twice as long to compile aot (9.5 minutes).   Uninstalling `angular2-justgage`, the app only takes 5 minutes to compile aot.

**Workaround**
Replace justgage with Angular Material 2 Progress Bar component (boo! hiss!)

**Compile-Time Error using --aot switch**
ERROR in ./node_modules/angular2-justgage/dist/justgage.component.ngfactory.ts
Module build failed: Error: C:\git-hcm\optimizer2\Presentation\node_modules\angular2-justgage\dist\justgage.component.ngfactory.ts is not part of the compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
    at AngularCompilerPlugin.getCompiledFile (C:\git-hcm\optimizer2\Presentation\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:620:23)
    at plugin.done.then (C:\git-hcm\optimizer2\Presentation\node_modules\@ngtools\webpack\src\loader.js:467:39)
    at <anonymous>
 @ ./src/app/_common/widgets/HcmRiskToleranceQuestionnaire/HcmRiskQuestionnaire.Component.ngfactory.js 17:0-102
 @ ./src/app/areas/signup/client/SignupClient.Component.ngfactory.js
 @ ./src/app/areas/signup/client/SignupClient.Module.ngfactory.js
 @ ./src/$$_lazy_route_resource lazy
 @ ./node_modules/@angular/core/esm5/core.js
 @ ./src/main.ts
 @ multi ./src/main.ts

**Environemnt**
OS: Windows 10
IDE: VisualStudio Code
Shell Type: PowerShell 
NPM Version: 5.3.0
NodeJS Version: 8.4.0
Webpack Version: 3.8.1

**Build Command**
`ng build --prod --aot --sourcemaps=false`

**JustGage Module**
`    "angular2-justgage": "^0.2.1",`

**Angular Modules**
`   "@angular/animations": "^5.0.3", `
`   "@angular/cdk": "^5.0.0-rc.1",`
`   "@angular/common": "^5.0.3",`
`   "@angular/compiler": "^5.0.3",`
`   "@angular/forms": "^5.0.3",`
`   "@angular/http": "^5.0.3",`
`   "@angular/material": "^5.0.0-rc.1",`
`   "@angular/platform-browser": "^5.0.3",`
`   "@angular/platform-browser-dynamic": "^5.0.3",`
`   "@angular/platform-server": "^5.0.3",`
`   "@angular/router": "^5.0.3",`

**tsconfig.json**
`{
    "compileOnSave": false,
    "compilerOptions": 
    {
        "outDir": "./dist/out-tsc",
        "sourceMap": true,
        "declaration": false,
        "moduleResolution": "node",
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "target": "es5",
        "typeRoots": 
        [
            "node_modules/@types"
        ],
        "lib": 
        [
            "es2017",
            "dom"
        ]
    }
}`

**Comment by emn178** [comment]
I will try to upgrade this in few days. thanks.

**Comment by emn178** [comment]
v0.3.0 should fix this. please try again

**Comment by hhmultimediallc** [comment]
Verified that component now compiles AOT without error in Angular 5.  Thank you so much, emn178!

**Comment by hhmultimediallc** [comment]
It is interesting that justgage seems causes our build to take twice as long to compile, though,

**Comment by emn178** [comment]
I can't reproduce. I only see build message once. I use an empty ng5 project and added justgage. It will add extra 4~5 seconds to build.
